### ISSUE TITLE
[BUG] Strange pagedoll visual glitch

### ISSUE THREAD

**Issue by DaxDoodles** [Sheezy-Art/sheezy-hub#122]
**Describe the Bug**
It looks like there is strange artifacting on the pagedol when its a Gif on Ipad

**To Reproduce**
1. Go to 'Profile with gif pagedol (on ipad)
2. See error

**Expected Behaviour**
See pagedoll as normal with no artifacting

**Screenshots**

https://media.discordapp.net/attachments/1153455394333663344/1190422479257227434/RPReplay_Final1703889179.mov?ex=65a1be54&is=658f4954&hm=30db437838f8125c64301147552ec0ae3bd812766e7fee4beeec082fdb937259&

**Device**
- Type: Ipad
 - OS: IOS
 - Browser: safari
 - Version: idk

**Comment by boylett** [comment]
I'm afraid this is an issue with the way you have exported the image. I see the same artefacts in my file browser when I download the image. I've optimised it for you - this should remove the artefacts. 

Try uploading this version (zipped because GitHub doesn't support WebP yet):
[dax-pagedoll-optimized.webp.zip](https://github.com/Sheezy-Art/sheezy-hub/files/13798760/dax-pagedoll-optimized.webp.zip)
