### ISSUE TITLE
[BUG] browsing trending posts not working on Opera GX

### ISSUE THREAD

**Issue by meatsleeps** [Sheezy-Art/sheezy-hub#378]
**Describe the Bug**
The browsing function isn't loading posts when sorting by what's trending.
Searching by 'oldest at the top' also strangely just shows all of the 'newest at the top' uploads instead of the oldest uploads.
I checked this out on Firefox and the trending tab is working just fine, so I assume this is an issue with Opera GX specificly.

**To Reproduce**
1. Go to sheezy homepage
2. Click on 'see more' for the trending tab
3. Trending tab doesn't load and gives an error message

**Expected Behaviour**
To be able to to see currently trending posts

**Screenshots**
![4493874fdb185b86d68071919346fa89](https://github.com/Sheezy-Art/sheezy-hub/assets/158549318/87abe706-a4bd-4689-9736-b91922c23026)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Opera GX
 - Version: 5

**Comment by boylett** [comment]
This error message appears when your page times out. It is likely due to a slow internet connection or other network issue. I'm actively working on making the artwork queries more efficient to try and mitigate this issue from the server side, but there's only so much that can be done on this end. Closing this for now as it is an ongoing WIP.
