### ISSUE TITLE
[BUG] Enthusiastic use of !!!!!!!'s turn into blocks in comments

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#382]
**Describe the Bug**
Use of multiple exclamation points in succession look like they turn into spoiler blocks (nothing is clickable).

**To Reproduce**
1. post a comment with lots of exclamation points
2. See error
3. [Here is the comment in question if you want to poke around with it](https://sheezy.art/comment/65be7e15c33babd286b305c8)

**Expected Behaviour**
!!!!!!!! are all visible : )
or for it to be a spoiler block

**Screenshots**
 https://cdn.discordapp.com/attachments/1191539111987777547/1203414109627097098/Screen_Shot_2024-02-03_at_12.57.32_PM.png?ex=65d101ba&is=65be8cba&hm=d822d0b0a56e12b4c21809864e17edbde4bad5593139af1cc6f48f4a0b01b8b8&
Left is the comment
Right is what it looks like in the edit box

**Device**
- Type: Laptop
 - OS: [e.g. Windows, iOS]
 - Browser: Firefox
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Full disclosure – this was happening because the 'Spoiler' functionality was using a gross, hacky workaround. Our markdown rendering engine, [MarkdownIt](https://github.com/markdown-it/markdown-it), does not allow the use of pipe characters (`|`) for anything other than tables. Because we are a heavily Discord-oriented community, I felt that a lot of us had gotten used to using `||` as the typical spoiler tagging format. My solution was to attempt to replace `||` with `!!` and let MarkdownIt do its thing. My oversight, however, was in assuming people wouldn't be using exclamation points so extremely liberally.

This solution sucks, and I know I can do better. So, for now, spoiler tags on sheezy use a much cleaner 'container block' format, wherein we wrap content to be spoilered in `::: spoiler` and `:::` to denote a spoiler block.

Unfortunately, this means we lose inline spoilers. But for now I think it's better to have a clean solution that doesn't use hacky workarounds. I'll continue to wrangle with MarkdownIt and see if I can come up with some kind of clean compromise regarding inline spoilers. Wish me luck!
