### ISSUE TITLE
[TODO] Add confirmation dialog to comments block delete button

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#74]
**Describe the Bug**
When deleting a comment block and adding it again later, the comment history of my profile vanishes.

**To Reproduce**
1. Go to profile
2. Edit Customization
3. Delete comment block
4. Re-add comment block
5. !! Comments gone!!

**Expected Behaviour**
Comment history to be saved per profile.

**Screenshots**
![firefox_vLrn2AG06p](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/ba075f7d-1226-4ef6-96d5-1839eab5ec50)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 120.0.1

**Comment by boylett** [comment]
This is an intended feature. Comments are now saved on a per-block basis rather than per-profile, so you can host multiple comments discussions on your profile if you want to.

Considering this is seen as a bug, however, I think adding a confirmation dialog to the 'delete' button for this block would be poignant.
