### ISSUE TITLE
[BUG] Dragging a profile block into specific spots breaks profile backgrounds.

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#76]
**Describe the Bug**
Ok, so this is a weird one where I don't know what happened, and trying to replicate it seemed to make things more broken haha.
When moving profile blocks, if I move a block (in this case, the featured artwork one) in the wrong place, it seems to make the background image bug out. In my case, it seems to take a background that was set to cover and superzoom it?
Reuploading doesn't seem to fix it and tbh I'm confused as to what is even happening so I'm sorry if this is a confusing report!!

**To Reproduce**
1. Edit profile.
3. Move a few blocks around.
4. Move a profile block in between "drop profile block(s) here" sections.
5. Watch as my fine page changes and image breaks?

**Expected Behaviour**
My background stays the same.

**Screenshots**
My background, set to cover, from a few days ago:
![vivaldi_XfCymkUs3t](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/3f648eac-b44a-41ea-91d0-499519600fe2)
Now:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/43ec1f6b-04d2-4b21-9a13-1e9fb1377839)

I can't really find any images that show it as good as my original background does, but when messing with other images I can tell _something_ is changing when I drag a block into that spot. 

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 120.0.1

**Comment by boylett** [comment]
The issue here is that the 'cover' background size forces the image to fit to the smallest dimension of the browser.

So if, for example, your background image is 1920 pixels wide and 1080 pixels high, but your browser window is 1300 wide by 1200 high, the image will stretch so that it matches the browser's height of 1200, because it is the smallest of the two. Its width will then match the image's aspect ratio, which is why your background image is bleeding off of the edges here.

You'll likely want to ensure that the central column of your wallpaper image is 1240 pixels wide - the max width of the profile column on desktop - and then set your background size to 'Image Size' (previously 'Auto').

This raises a future enhancement opportunity - I'd like to either do some more complex maths with the background size to make it scale responsively with the browser, or offer the user a way to upload a separate background image for tablets and mobile devices. Have added that as a todo (#102).
