### ISSUE TITLE
[BUG] Recently Gallery doesn't display recent

### ISSUE THREAD

**Issue by Stormeko** [Sheezy-Art/sheezy-hub#86]
**Describe the Bug**
If you have the Gallery block set to Most Recent with Newest At Top, it doesn't display your newest works. What's displayed seems to change depending on how many rows and columns you set it to

**To Reproduce**
1. Add the Gallery Block to your page
2. Set the drop downs to My Most Recent Art Works and Newest At The Top
3. Save and return to profile
4. The Gallery block doesn't display the most recent artwork

**Expected Behaviour**
The Gallery block should display your most recently uploaded art

**Screenshots**
Gallery Block
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317217/3a658a51-9c10-4320-8017-ade40ed85d93)

Gallery itself
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317217/2266633a-d46c-4902-beb6-037698c13693)

**Device**
- Type: Laptop
 - OS: Win10
 - Browser: Firefox
 - Version: Latest

**Comment by geoledgy** [comment]
Hi! Not sure if I am doing this right/if there is a format for comments but I was told to comment here. I'm having a possibly similar issue with the profile gallery blocks where the number of rows isn't correctly displaying. When it's set to "random", it adds 2 extra rows, while "trending" adds 1 extra row. It displays the correct type of artwork expected though (trending displays trending, random displays random)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/132530080/3e51761c-0174-4e2d-8432-98c6afe7a96a)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/132530080/8065eec6-6ffa-48f2-9c9a-0d34669545dc)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/132530080/d2e98183-13ab-4ae1-bd23-a111ce8b399d)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/132530080/fd9c1650-cf56-4e1a-a987-c65d770d9c50)

Expected behavior is that there should be the correct number of rows in the profile blocks (in my case, 1 row)
